# This is a basic workflow to help you get started with Actions

name: Build

on:
  workflow_call:
    inputs:
      build_only_when_update_available:
        required: false
        default: false
        type: boolean
      build_number:
        required: false
        default: ""
        type: string
      public_cert_base64:
        required: true
        type: string
      channel:
        required: false
        default: "Stable"
        type: string
    secrets:
      private_key_pfx_base64:
        required: true
      private_key_password:
        required: true



permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4.1.2
        name: checkout
        with:
          fetch-depth: 0

      - uses: WyriHaximus/github-action-get-previous-tag@v1
        name: get previous tag
        id: previoustag
        with:
          fallback: 1.0.0.0
          prefix: ${{ inputs.channel }}_

      - shell: pwsh
        name: get previous tag and timestamp
        id: previoustag_timestamp
        run: |
          if("${{ steps.previoustag.outputs.tag }}" -eq "0"){ Write-Output "::set-output name=TAG::1.0.0.0";  Write-Output "::set-output name=TIMESTAMP::0"}
          if("${{ steps.previoustag.outputs.tag }}" -ne "0"){ Write-Output "::set-output name=TAG::${{ steps.previoustag.outputs.tag }}";  Write-Output "::set-output name=TIMESTAMP::${{ steps.previoustag.outputs.timestamp }}"}

      - shell: pwsh
        name: install psake
        run: |
          set-psrepository psgallery -installationpolicy trusted
          Install-Module -Name psake -repository psgallery

      - shell: pwsh
        name: get previous version from tag
        id: previous_version
        run: |
          $tag = "${{ steps.previoustag_timestamp.outputs.TAG }}"
          $tag -match "^.*?([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)"
          $ver = $matches[1]
          Write-Output "::set-output name=PREV_VERSION::$($ver)"

      - shell: pwsh
        name: check for package updates
        if: ${{ inputs.build_only_when_update_available }}
        id: check_update
        run: |
          Import-Module psake
          invoke-psake ./build.ps1 -task CanUpdate -parameters @{"previous_package_version"="${{ steps.previous_version.outputs.PREV_VERSION }}";"channel"="${{ inputs.channel }}"}
          Write-Output "::set-output name=UPDATE_AVAILABLE::$($psake.build_success)"

      - shell: pwsh
        name: build
        id: build
        if: ${{ ! inputs.build_only_when_update_available || steps.check_update.outputs.UPDATE_AVAILABLE == 'True' }}
        run: |
          $VsInstance = Get-VsSetupInstance -All | Select-VsSetupInstance -Latest
          & "$($VsInstance.InstallationPath)\Common7\Tools\Launch-VsDevShell.ps1" -SkipAutomaticLocation
          Import-Module psake
          invoke-psake ./build.ps1 -parameters @{"cert_base64"="${{ secrets.private_key_pfx_base64 }}";"cert_password"="${{ secrets.private_key_password }}";"public_cert_base64"="${{ inputs.public_cert_base64 }}";"package_name"="SublimeText";"previous_package_version"="${{ steps.previous_version.outputs.PREV_VERSION }}";"build_number_override"="${{ inputs.build_number }}";"previous_package_timestamp"="${{ steps.previoustag_timestamp.outputs.TIMESTAMP }}";"channel"="${{ inputs.channel }}"}
          Write-Output "::set-output name=BUILD_SUCCESS::$($psake.build_success)"
        
      - shell: pwsh
        name: get release info
        id: get_release_info
        if: ${{ steps.build.outputs.BUILD_SUCCESS == 'True' }}
        run: |
          $tag_name = "${{ inputs.channel }}_$(Get-Content -Path ./out/version.txt)"
          Write-Output "::set-output name=TAG_NAME::$($tag_name)"
          Write-Output "::set-output name=TITLE::Sublime Text ${{ inputs.channel }} ($($tag_name))"

      - shell: pwsh
        name: make dev appinstaller and release note
        if: ${{ steps.build.outputs.BUILD_SUCCESS == 'True' && inputs.channel == 'Dev'}}
        run: |
          $ver = Get-Content -Path ./out/version.txt
          $package_base_url = "${{ github.server_url }}/${{ github.repository }}/releases/download/${{ steps.get_release_info.outputs.TAG_NAME }}"
          $appinstaller_base_url = "${{ github.server_url }}/${{ github.repository }}/releases/download/Dev_Latest"
          Import-Module psake
          Invoke-Psake build.ps1 -task MakeAppInstallerAndReleaseNote -parameters @{"changelog_path_override"="./out/SublimeText_changelog.html";"package_version"="$($ver)";"package_base_url"="$($package_base_url)";"appinstaller_base_url"="$($appinstaller_base_url)";"cert_base64"="${{ secrets.private_key_pfx_base64 }}";"cert_password"="${{ secrets.private_key_password }}"}

      - shell: pwsh
        name: make stable appinstaller and release note 
        if: ${{ steps.build.outputs.BUILD_SUCCESS == 'True' && inputs.channel == 'Stable'}}
        run: |
          $ver = Get-Content -Path ./out/version.txt
          $package_base_url = "${{ github.server_url }}/${{ github.repository }}/releases/download/${{ steps.get_release_info.outputs.TAG_NAME }}"
          $appinstaller_base_url = "${{ github.server_url }}/${{ github.repository }}/releases/latest/download"
          Import-Module psake 
          Invoke-Psake build.ps1 -task MakeAppInstallerAndReleaseNote -parameters @{"changelog_path_override"="./out/SublimeText_changelog.html";"package_version"="$($ver)";"package_base_url"="$($package_base_url)";"appinstaller_base_url"="$($appinstaller_base_url)";"cert_base64"="${{ secrets.private_key_pfx_base64 }}";"cert_password"="${{ secrets.private_key_password }}"}

      - uses: ncipollo/release-action@v1.14.0
        name: create stable release
        if: ${{ steps.build.outputs.BUILD_SUCCESS == 'True' && inputs.channel == 'Stable'}}
        with:
          makeLatest: true
          artifacts: out/*.crt,out/*.msix,out/*.appinstaller
          commit: master
          tag: ${{ steps.get_release_info.outputs.TAG_NAME }}
          name: ${{ steps.get_release_info.outputs.TITLE }}
          bodyFile: out/SublimeText_release_note.html

      - uses: ncipollo/release-action@v1.14.0
        name: update latest dev release
        if: ${{ steps.build.outputs.BUILD_SUCCESS == 'True' && inputs.channel == 'Dev'}}
        with:
          prerelease: true
          makeLatest: false
          removeArtifacts: true
          replaceArtifacts: true
          allowUpdates: true
          artifacts: out/*.crt,out/*.msix,out/*.appinstaller
          commit: master
          tag: Dev_Latest
          name: Latest Sublime Text Dev (${{ steps.get_release_info.outputs.TITLE }})
          bodyFile: out/SublimeText_release_note.html

      - uses: ncipollo/release-action@v1.14.0
        name: create dev release
        if: ${{ steps.build.outputs.BUILD_SUCCESS == 'True' && inputs.channel == 'Dev'}}
        with:
          prerelease: true
          makeLatest: false
          artifacts: out/*.crt,out/*.msix,out/*.appinstaller
          commit: master
          tag: ${{ steps.get_release_info.outputs.TAG_NAME }}
          name: ${{ steps.get_release_info.outputs.TITLE }}
          bodyFile: out/SublimeText_release_note.html


